---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Malandain.
--- DateTime: 29/08/2019 00:08
---

RMenu.Add("personnal", "main", RageUI.CreateMenu("RainLayer City", "Actions disponibles", 0, 10, nil, nil, 215, 185, 165, 1.0))


--RMenu.Add('personnal', 'inventory', RageUI.CreateMenu("RainLayer City", "Actions disponibles"))

--RMenu.Add('personnal', 'inventory', RageUI.CreateMenu("RainLayer City", "Actions disponibles"))

Citizen.CreateThread(
    function()
        while true do
            Wait(1)

            if RageUI.Visible(RMenu:Get("personnal", "main")) then
                RageUI.DrawContent(
                    {header = true, glare = true},
                    function()
                        RageUI.Button(
                            "Inventaire",
                            nil,
                            {RightLabel = "→→"},
                            true,
                            function(_, _, Selected)
                                if Selected then
                                    if LocalPlayer().Handcuff then
                                        CloseAllMenus()
                                        ShowNotification("~r~Vous ne pouvez pas faire ça")
                                    end
                                end
                            end,
                            RMenu:Get("personnal", "inventory")
                        )

                        RageUI.Button(
                            "Animations",
                            nil,
                            {RightLabel = "→→"},
                            true,
                            function(_, _, Selected)
                                if Selected then
                                    if LocalPlayer().Handcuff then
                                        CloseAllMenus()
                                        ShowNotification("~r~Vous ne pouvez pas faire ça")
                                    end
                                end
                            end,
                            RMenu:Get("personnal", "animations")
                        )

                        RageUI.Button(
                            "Actions",
                            nil,
                            {RightLabel = "→→"},
                            true,
                            function(_, _, Selected)
                                if Selected then
                                    if LocalPlayer().Handcuff then
                                        CloseAllMenus()
                                        ShowNotification("~r~Vous ne pouvez pas faire ça")
                                    end
                                end
                            end,
                            RMenu:Get("personnal", "actions")
                        )

                        RageUI.Button(
                            "Informations",
                            nil,
                            {RightLabel = "→→"},
                            true,
                            function(_, _, Selected)
                                if Selected then
                                end
                            end,
                            RMenu:Get("personnal", "infos")
                        )

                        RageUI.Button(
                            "Préférence",
                            nil,
                            {RightLabel = "→→"},
                            true,
                            function(_, _, Selected)
                            end,
                            RMenu:Get("personnal", "settings")
                        )
                        if GetVehiclePedIsIn(PlayerPedId()) ~= 0 then
                            RageUI.Button(
                                "Véhicule",
                                nil,
                                {RightLabel = "→→"},
                                true,
                                function(_, _, Selected)
                                end,
                                RMenu:Get("personnal", "vehicule")
                            )
                        end
                        if PlyGroup == "superadmin" then
                            RageUI.Button(
                                "Administration",
                                nil,
                                {RightLabel = "→→"},
                                true,
                                function(_, _, Selected)
                                end,
                                RMenu:Get("personnal", "admin")
                            )
                        end
                    end,
                    function()
                    end
                )
            end
        end
    end
)
function GetGroup()
    return PlyGroup
end

function OpenPersonnalMenu()
    RageUI.Visible(RMenu:Get("personnal", "main"), not RageUI.Visible(RMenu:Get("personnal", "main")))
end

RegisterCommand(
    "+personnal",
    function()
        OpenPersonnalMenu()
    end,
    false
)
RegisterCommand(
    "-personnal",
    function()
        OpenPersonnalMenu()
    end,
    false
)
RegisterCommand(
    "personnal",
    function()
        OpenPersonnalMenu()
    end,
    false
)
RegisterKeyMapping("personnal", "Menu personnel", "keyboard", "F5")
